### ISSUE TITLE
Lite/Full split: eliminate all TODOs from the specification

### ISSUE THREAD

**Issue by Ladicek** [eclipse-ee4j/cdi#482]
This is an umbrella issue to track the work on eliminating all TODO comments from the CDI specification Asciidoc sources, added in the initial Lite/Full split PR (#470). More sub-issues will be created and this issue will list them (and their status) to provide an overview.

- [x] #490 Lite/Full split: finish preface
- [x] #483 Lite/Full split: define packaging/deployment/lifecycle
- [x] #484 Lite/Full split: define new extension API
- [x] #485 Lite/Full split: decide on Portable Extensions mentions in the CDI Lite spec part
- [x] #486 Lite/Full split: decide on passivation mentions in the CDI Lite spec part
- [x] #489 Lite/Full split: decide on other mentions of Full-only concepts in the CDI Lite spec part
- [x] #487 Lite/Full split: make @Singleton a bean defining annotation?
- [x] #488 Lite/Full split: does CDI in Java SE environment (SeContainer etc.) have to support Full?
- [x] #491 Lite/Full split: decide on "Inter-module injection in CDI Full"
- [x] #492 Lite/Full split: decide on "Unsatisfied and ambiguous dependencies"
- [x] #493 Lite/Full split: decide on "The `EventMetadata` interface"
- [x] #494 Lite/Full split: decide on "Defining new scope types"

Personal opinion: I have added the TODO comments instead of just Asciidoc admonitions, because that allows easy tracking of the number of remaining open items (single `grep` command). I don't mind putting the content of the TODO comments into admonitions (and leaving an empty TODO comment alongside), but I believe this should all be primarily present directly in the Asciidoc source, so that context is immediately obvious. Tracking in GitHub issues is, in my opinion, secondary.

**Comment by manovotn** [comment]
All parts of this issue were done, closing now.
